spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nbastats
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 20
  jackson:
    serialization:
      INDENT_OUTPUT: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: nba-stats-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
info:
  title: NBA Stats API
  description: Backend for logging and aggregating NBA player statistics
  version: 0.0.1

logging:
  level:
    root: INFO
    org.apache.kafka: INFO
    org.springframework.kafka: INFO
    org.testcontainers: INFO

server:
  port: 8080