spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nbastats
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 20
  jackson:
    serialization:
      INDENT_OUTPUT: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: nba-stats-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.matias.kreiman.nbastats.dto
      listener:
        type: batch
        #aligned with the number of partitions on the topic
        concurrency: 1
        #to PROD
        #concurrency: 3
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080